/**
 * OpenAgent V2 - Orchestrator Types
 *
 * Types for the orchestrator that plans, dispatches, and monitors multi-worker execution.
 */

import type { WorkerRole } from '@openagent/worker';
import type { TaskPriority } from '@openagent/queue';

// =============================================================================
// PLAN
// =============================================================================

/**
 * A step in an execution plan.
 */
export interface PlanStep {
  /** Unique step ID */
  id: string;

  /** Human-readable title */
  title: string;

  /** Description of what this step does */
  description: string;

  /** Which worker role should execute this step */
  assignTo: WorkerRole;

  /** Task priority */
  priority: TaskPriority;

  /** IDs of steps this step depends on */
  dependencies: string[];

  /** The prompt to send to the worker */
  prompt: string;
}

/**
 * An execution plan generated by the planner.
 */
export interface ExecutionPlan {
  /** Plan ID */
  id: string;

  /** Original user request */
  request: string;

  /** Steps in the plan */
  steps: PlanStep[];

  /** When the plan was created */
  createdAt: Date;
}

// =============================================================================
// EXECUTION RESULT
// =============================================================================

/**
 * Result of executing a single step.
 */
export interface StepResult {
  stepId: string;
  status: 'completed' | 'failed';
  output?: string;
  error?: string;
  duration: number;
}

/**
 * Overall result of executing a plan.
 */
export interface OrchestratorResult {
  /** Plan ID */
  planId: string;

  /** Whether execution succeeded */
  success: boolean;

  /** Results of each step */
  stepResults: StepResult[];

  /** Total execution time in ms */
  totalDuration: number;

  /** Summary of what was accomplished */
  summary: string;
}

// =============================================================================
// ORCHESTRATOR CONFIG
// =============================================================================

/**
 * Configuration for the orchestrator.
 */
export interface OrchestratorConfig {
  /** Maximum parallel workers */
  maxParallelWorkers?: number;

  /** Task timeout in ms (default: 5 minutes) */
  taskTimeoutMs?: number;

  /** Whether to require plan approval before execution */
  requireApproval?: boolean;

  /** Maximum retries per step */
  maxRetries?: number;
}

// =============================================================================
// ORCHESTRATOR DEPENDENCIES
// =============================================================================

/**
 * Dependencies injected into the orchestrator.
 */
export interface OrchestratorDeps {
  /** LLM router for planner */
  router: import('@openagent/llm').LLMRouter;

  /** Tool registry for workers */
  tools: import('@openagent/tools').IToolRegistry;

  /** Message bus for events */
  bus: import('@openagent/message-bus').IMessageBus;

  /** Optional memory store */
  memoryStore?: import('@openagent/memory').IMemoryStore;

  /** Optional artifact store */
  artifactStore?: import('@openagent/artifact').IArtifactStore;
}
